spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/recipe-book-db
    username: jim
    password: password

  data:
    mongodb:
      host: localhost
      port: 27017
      username: jim
      password: root_password
      database: recipe-book-db
      authentication-database: admin

  flyway:
    user: jim
    password: password
    url: jdbc:mariadb://localhost:3306/recipe-book-db
    locations: classpath:db.migration

server:
  port: 8080
